### ISSUE TITLE
Xml::WriteToFile() failed

### ISSUE THREAD

**Issue by Trash-J** [bittnerma/Direct3DKinematicEstimation#4]
When running `generate_opensim_gt.py`, I get the following error:

```Traceback (most recent call last):
  File "C:\Robotics\Q3\Deep Learning\Project\Direct3DKinematicEstimation\ms_model_estimation\opensim_utils\OpenSimModel.py", line 444, in scaling
    success = scaleTool.run()
  File "C:\OpenSim4.4\sdk\Python\opensim\tools.py", line 2246, in run
    return _tools.ScaleTool_run(self)
RuntimeError: std::exception in 'bool OpenSim::ScaleTool::run() const': SimTK Exception thrown at Xml.cpp:115:
  Error detected by Simbody method Xml::writeToFile(): Failed to write to the Xml file 'resources/opensim/BMLmovi/BMLmovi/Subject_11_F_MoSh/scale.osim' with error ' (line=1, col=1)'.
  (Required condition 'saveOK' was not met.)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\generate_opensim_gt.py", line 45, in <module>
    gtGenerator.generate(path)
  File "C:\Robotics\Q3\Deep Learning\Project\Direct3DKinematicEstimation\ms_model_estimation\opensim_utils\OSLabelGenerator.py", line 336, in generate
    super().generate(bdataPath, gender)
  File "C:\Robotics\Q3\Deep Learning\Project\Direct3DKinematicEstimation\ms_model_estimation\opensim_utils\OSLabelGenerator.py", line 130, in generate
    self.opensimModel.scaling()
  File "C:\Robotics\Q3\Deep Learning\Project\Direct3DKinematicEstimation\ms_model_estimation\opensim_utils\OpenSimModel.py", line 446, in scaling
    raise Exception("Body scaling fails!")
Exception: Body scaling fails!
```

how do I fix this?

**Comment by bittnerma** [comment]
Reason was that '__file__' when started from the VS Code Run Script button will return the full path, while when running from command line will only return the relative part of the file. Commit fb534fbd606031dc96ffcdadbfe9c3843116bcdb
should fix this.
